### ISSUE TITLE
Knob move to the end automatically

### ISSUE THREAD

**Issue by Pakyyy** [AZOPCORP/fancyknob#1]
Everything works fine when I initialized the knob and turn it, but when I try to turn the knob for the second time, the knob first returns to the end (minimum value or maximum value), then start to move.

It seems that the css style transform: rotate return to certain value every time I try to move the knob. And I'm not sure if I was loading the js wrong or something.

**Comment by Pakyyy** [comment]
I added some line to saved the currentDeg so the knob will not returns to minimum or maximum. Problem solved and will try to post it later.

Thanks for the awesome knob anyway!

**Comment by AZOPCORP** [comment]
Thanks please submit a merge request if you fixed the bug.

**Comment by Pakyyy** [comment]
Sorry that I'm very busy recently and got no time to update.
I have submitted a PR for the fix, please let me know if I missed anything. Cheer~
https://github.com/AZOPCORP/fancyknob/pull/2
